
###################################################################
#  Makefile for Lab 2
#
#  Abu Talha
#  SMU Mathematics
#  Math 6370
###################################################################


driver.exe : driver.cpp

	g++ -c driver.cpp one_norm.cpp vector_difference.cpp vector_product.cpp vector_sum.cpp
	g++ -o driver.exe driver.o one_norm.o vector_difference.o vector_product.o vector_sum.o -lm 
 

clean: 
	rm -f *.o *.exe


####### End of Makefile #######
	

